name: "Protocol Buffer Go Stubs Generation"
on:
  push:
    tags:
      - 'v**'

jobs:
  protoc:
    name: "Generate"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["order", "payment", "shipping"]
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.4

      - uses: actions/checkout@v2

      - name: Extract Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Install Make
        run: sudo apt-get install -y make

      - name: Generate directories
        run: make init

      - name: Generate Protobuf Stubs and Update Go Modules
        run: make generate_${{ matrix.service }} SERVICE_NAME=${{ matrix.service }} RELEASE_VERSION=${{ env.RELEASE_VERSION }}
      
      - name: Create Go Modules for ${{ matrix.service }}
        run: make create_modules_${{ matrix.service }}
      
      - name: update repo
        run: make update-repo SERVICE_NAME=${{ matrix.service }} RELEASE_VERSION=${{ env.RELEASE_VERSION }}