name: "Protocol Buffer Go Stubs Generation"
on:
  push:
    tags:
      - 'v**'

jobs:
  protoc:
    name: "Generate"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["order", "payment", "shipping"]
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.4

      - uses: actions/checkout@v2

      - name: Extract Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Install Protocol Buffer Compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - name: Install Make
        run: sudo apt-get install -y make

      - name: Initialize Directories
        run: make init

      - name: Generate Protobuf Stubs for ${{ matrix.service }}
        run: make generate_${{ matrix.service }}

      - name: Create Go Modules for ${{ matrix.service }}
        run: make create_modules_${{ matrix.service }}
