name: "Protocol Buffer Go Stubs Generation"
on:
  push:
    tags:
      - 'v**'

jobs:
  code-gen:
    name: "Generate"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["order", "payment", "shipping"]
    steps:

      - name: Extract Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Install Make
        run: sudo apt-get install -y make

      - name: make
        run: make all  SERVICE_NAME=${{ matrix.service }} RELEASE_VERSION=${{ env.RELEASE_VERSION }}
      